# User Features

In [1]:
import pandas as pd

# From User Table direct (Jacklynn)

In [43]:
users = pd.read_csv("../data_preprocessed/users_preprocessed.csv")[["user_id", "married", "has_children", "age", "gender"]]

# Avg Baggage (Boris)

In [2]:
flights = pd.read_csv("../data_preprocessed/flights_preprocessed.csv")

In [3]:
sessions = pd.read_csv("../data_preprocessed/sessions_preprocessed.csv")

In [4]:
sessions

,session_id,user_id,trip_id,session_start,session_end,flight_discount,hotel_discount,flight_discount_amount,hotel_discount_amount,flight_booked,hotel_booked,page_clicks,cancellation
0,559164-e4d39929bc6040b1b58e2f774b807348,559164,559164-ae58e1fbf8db4f27846fb70c8308ee40,2023-04-02 19:56:00,2023-04-02 19:59:49,False,False,NaN,NaN,True,True,31,False
1,559469-2027a778257341c280db87d26ce9e4e3,559469,559469-aa0fd2b0ee2a403f82e3cf84388c2da3,2023-04-02 12:56:00,2023-04-02 12:57:39,False,False,NaN,NaN,True,False,13,False
2,561331-fb661b0fa33449a187f26b438658a6a5,561331,561331-6478dc007052490e87afee54982c434f,2023-04-02 18:08:00,2023-04-02 18:10:01,False,True,NaN,0.10,True,True,16,False
3,563052-7a1cec53282d404d95495a12bb0de14f,563052,NaN,2023-04-02 20:18:00,2023-04-02 20:19:18,False,True,NaN,0.15,False,False,11,False
4,565460-f25739901563474aa9f4dbad1cc295bf,565460,NaN,2023-04-02 17:09:00,2023-04-02 17:10:35,False,True,NaN,0.10,False,False,13,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49206,543716-c0a36a0263c24262a2ea76f07a8b995f,543716,543716-cefacd82315843a1a083e1bb070e1e11,2023-04-02 20:03:00,2023-04-02 20:05:35,False,False,NaN,NaN,True,True,21,False
49207,545318-3e9a87cf93164fe48f5a650b7dbd35cd,545318,NaN,2023-04-02 20:14:00,2023-04-02 20:16:42,False,False,NaN,NaN,False,False,22,False
49208,549235-32a0d455a8c04e458a621dd2999ea246,549235,NaN,2023-04-02 10:00:00,2023-04-02 10:00:58,False,False,NaN,NaN,False,False,8,False
49209,551600-250e4ebe55b842919c95ea1f995ae652,551600,NaN,2023-04-02 21:32:00,2023-04-02 21:33:15,True,False,0.2,NaN,False,False,10,False
49210,551718-9d071b7f2d0c43dc9d2592eeea827dba,551718,NaN,2023-04-02 01:15:00,2023-04-02 01:15:24,False,False,NaN,NaN,False,False,3,False

In [5]:
flights

,trip_id,origin_airport,destination,destination_airport,seats,return_flight_booked,departure_time,return_time,checked_bags,trip_airline,destination_airport_lat,destination_airport_lon,base_fare_usd,distance_km,base_fare_usd_pp,base_usd_pp_per_km
0,204943-07ddf3a4d2a34e03befdbd07c78d9aab,YOW,new york,LGA,3,True,2023-03-06 07:00:00,2023-03-09 07:00:00,0,KLM Royal Dutch Airlines,40.640,-73.779,267.58,526.036985,89.193333,0.169557
1,229330-b73ffe29221b40a086cd0107f85eac2b,COS,san antonio,RND,1,True,2023-02-26 15:00:00,2023-03-02 15:00:00,0,United Airlines,29.529,-98.279,213.01,1187.884946,213.010000,0.179319
2,283325-dd763c2d6d334b3790266b500393438e,DAL,quebec,YQB,1,True,2023-03-05 14:00:00,2023-03-11 14:00:00,0,Air Canada,46.788,-71.398,453.27,2650.882368,453.270000,0.170988
3,347778-1bc6f3542683460480d91602d0a05a22,LSV,san diego,NZY,1,True,2023-06-26 11:00:00,2023-06-29 11:00:00,1,Ryanair,32.699,-117.215,77.49,441.165331,77.490000,0.175648
4,389434-cf10e38f0d464b81ace3f3be9f689833,LGA,hamilton,YHM,1,True,2023-04-06 07:00:00,2023-04-07 07:00:00,1,WestJet,43.173,-79.935,105.77,567.389136,105.770000,0.186415
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13712,679066-34fe218a3ebf429795d788fe6d1b4319,MXF,el paso,ELP,1,True,2023-06-30 11:00:00,2023-07-02 11:00:00,1,Air France,31.849,-106.380,301.52,1883.509967,301.520000,0.160084
13713,698573-1ab935d1f3c146ffbbf6fdeeb2415e33,EWR,new york,LGA,1,True,2023-06-08 11:00:00,2023-06-19 11:00:00,0,JetBlue Airways,40.640,-73.779,6.53,26.667162,6.530000,0.244870
13714,767426-33cd5443192c434d96a21f558b068009,FYV,new york,JFK,3,True,2023-06-14 09:00:00,2023-06-16 09:00:00,0,Delta Air Lines,40.640,-73.779,990.19,1847.124018,330.063333,0.178690
13715,774666-b8e9ae456e874a5eaa038863565178fb,MSP,toronto,YTZ,1,True,2023-06-27 07:00:00,2023-06-29 07:00:00,1,Porter Airlines,43.862,-79.370,197.13,1108.518937,197.130000,0.177832
13716,785107-de5d44027081481297469221ef8794ba,PDX,houston,EFD,1,True,2023-05-09 09:00:00,2023-05-11 09:00:00,1,American Airlines,29.607,-95.159,524.73,2975.547493,524.730000,0.176347

In [6]:
flights = flights.merge(sessions[["user_id", "trip_id"]], on="trip_id")

In [7]:
avg_bags_feature = flights.groupby("user_id")["checked_bags"].mean()  # Feature

# Cancellation Rate (Thomas)

In [48]:
sessions

,session_id,user_id,trip_id,session_start,session_end,flight_discount,hotel_discount,flight_discount_amount,hotel_discount_amount,flight_booked,hotel_booked,page_clicks,cancellation
0,559164-e4d39929bc6040b1b58e2f774b807348,559164,559164-ae58e1fbf8db4f27846fb70c8308ee40,2023-04-02 19:56:00,2023-04-02 19:59:49,False,False,NaN,NaN,True,True,31,False
1,559469-2027a778257341c280db87d26ce9e4e3,559469,559469-aa0fd2b0ee2a403f82e3cf84388c2da3,2023-04-02 12:56:00,2023-04-02 12:57:39,False,False,NaN,NaN,True,False,13,False
2,561331-fb661b0fa33449a187f26b438658a6a5,561331,561331-6478dc007052490e87afee54982c434f,2023-04-02 18:08:00,2023-04-02 18:10:01,False,True,NaN,0.10,True,True,16,False
3,563052-7a1cec53282d404d95495a12bb0de14f,563052,NaN,2023-04-02 20:18:00,2023-04-02 20:19:18,False,True,NaN,0.15,False,False,11,False
4,565460-f25739901563474aa9f4dbad1cc295bf,565460,NaN,2023-04-02 17:09:00,2023-04-02 17:10:35,False,True,NaN,0.10,False,False,13,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49206,543716-c0a36a0263c24262a2ea76f07a8b995f,543716,543716-cefacd82315843a1a083e1bb070e1e11,2023-04-02 20:03:00,2023-04-02 20:05:35,False,False,NaN,NaN,True,True,21,False
49207,545318-3e9a87cf93164fe48f5a650b7dbd35cd,545318,NaN,2023-04-02 20:14:00,2023-04-02 20:16:42,False,False,NaN,NaN,False,False,22,False
49208,549235-32a0d455a8c04e458a621dd2999ea246,549235,NaN,2023-04-02 10:00:00,2023-04-02 10:00:58,False,False,NaN,NaN,False,False,8,False
49209,551600-250e4ebe55b842919c95ea1f995ae652,551600,NaN,2023-04-02 21:32:00,2023-04-02 21:33:15,True,False,0.2,NaN,False,False,10,False
49210,551718-9d071b7f2d0c43dc9d2592eeea827dba,551718,NaN,2023-04-02 01:15:00,2023-04-02 01:15:24,False,False,NaN,NaN,False,False,3,False

In [49]:
sessions["trip_id"].duplicated()

0        False
1        False
2        False
3        False
4         True
         ...
49206    False
49207     True
49208     True
49209     True
49210     True
Name: trip_id, Length: 49211, dtype: bool

In [50]:
sessions[sessions["trip_id"].duplicated(keep=False)].dropna(subset=['trip_id'])["trip_id"].value_counts().unique()

array([2])

In [51]:
sessions[sessions["cancellation"]]["trip_id"]

7899     174997-a7c3a96620594e849a2345ac4e0bd45d
7900     204997-303a3759d5814673b7c60db793d46cdd
7901     468409-a54d1d56a17e44448932f672f63305f9
7902     510108-e7b4f09ea9b748188803fc01aa07dfa0
7903     508912-613c5162eb974872a30e3b67f00d2360
                          ...
32880    694265-442d6499b511481786add276f620d4fc
32881    589228-7cbd8bd73eed4c549a0074919e71fdc8
32882    671151-a25acb9062764a168fbd4286d15d57fd
32883    609393-b92d487037ec447db1e3ddf977709a52
32884    591582-61f9e9bfb2dd461989dacc9f5b76371b
Name: trip_id, Length: 610, dtype: str

In [52]:
cancelled_trip_ids = sessions[sessions["cancellation"]]["trip_id"]

In [53]:
cancelled_trip_ids

7899     174997-a7c3a96620594e849a2345ac4e0bd45d
7900     204997-303a3759d5814673b7c60db793d46cdd
7901     468409-a54d1d56a17e44448932f672f63305f9
7902     510108-e7b4f09ea9b748188803fc01aa07dfa0
7903     508912-613c5162eb974872a30e3b67f00d2360
                          ...
32880    694265-442d6499b511481786add276f620d4fc
32881    589228-7cbd8bd73eed4c549a0074919e71fdc8
32882    671151-a25acb9062764a168fbd4286d15d57fd
32883    609393-b92d487037ec447db1e3ddf977709a52
32884    591582-61f9e9bfb2dd461989dacc9f5b76371b
Name: trip_id, Length: 610, dtype: str

In [54]:
sessions[sessions["trip_id"].isin(cancelled_trip_ids)]

,session_id,user_id,trip_id,session_start,session_end,flight_discount,hotel_discount,flight_discount_amount,hotel_discount_amount,flight_booked,hotel_booked,page_clicks,cancellation
10,581679-9878bbdbe65f4795b74c59895d240f1f,581679,581679-4bfc3cd149aa445cb61a5d485bd75ce2,2023-04-02 22:06:00,2023-04-02 22:07:06,False,True,NaN,0.1,True,False,9,False
44,429375-4c112e59d8014f9885bdabc4428dec24,429375,429375-dda8c0ffd53d493b8626d799e1b459a8,2023-04-03 15:24:00,2023-04-03 15:26:36,False,False,NaN,NaN,True,False,21,False
46,474120-a10bfd54afa84d3e9d6077359f180c01,474120,474120-6d1466f897ce4ee5970330510330c518,2023-04-03 20:20:00,2023-04-03 20:34:38,False,False,NaN,NaN,True,True,120,False
47,492497-b873ffe08d21466195a8699fbac072b7,492497,492497-8f9d6591afae43ae91c1253a98138e4f,2023-04-03 16:25:00,2023-04-03 16:29:05,False,False,NaN,NaN,True,False,32,False
196,512147-84cd055216f74497aaf119c9b59bffe1,512147,512147-aef346ffaf414cdcbc367aac71510515,2023-04-05 02:27:00,2023-04-05 02:38:35,False,False,NaN,NaN,True,True,93,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49003,521331-2bff7d21e7a2496cae0ee455e0f476a7,521331,521331-bef50434aea9451e9b18b9f475f527bb,2023-03-31 03:51:00,2023-03-31 03:52:06,False,False,NaN,NaN,True,False,9,False
49011,525555-b4667b4b51f64a4fa3ca16254ac2de7d,525555,525555-10faabe248514457a076b07794999573,2023-03-31 16:13:00,2023-03-31 16:24:59,False,False,NaN,NaN,True,False,98,False
49042,547130-b23bc79758a24f17b2f3d54e3cc47681,547130,547130-37230686229d4d0aacff29cfa6e8ae00,2023-03-31 19:15:00,2023-03-31 19:17:01,False,False,NaN,NaN,True,False,16,False
49050,553985-f0e5a84386c54d4c837cbf0bfdcbcf42,553985,553985-762dd6b6f2874d2cb46469707a9bcf81,2023-03-31 22:36:00,2023-03-31 22:52:55,False,False,NaN,NaN,True,True,136,False
49096,608343-3c51c6c0786344819a772c638763b605,608343,608343-5aebcff9ea354015a90f6b75f123f4c4,2023-03-31 19:44:00,2023-03-31 19:55:19,False,False,NaN,NaN,True,True,91,False

In [14]:
sessions["cancellation"].sum()

np.int64(610)

In [ ]:
sessions.groupby("user_id")["trip_id"].nunique()

user_id
23557     2
94883     2
101486    2
101961    5
106907    1
         ..
792549    4
796032    3
801660    3
811077    1
844489    0
Name: trip_id, Length: 5998, dtype: int64

In [55]:
cancellation_rate_feature = sessions.groupby("user_id")["cancellation"].sum()/sessions.groupby("user_id")["trip_id"].nunique()  # Feature

# Conversion rate (Mark)

In [28]:
sessions

,session_id,user_id,trip_id,session_start,session_end,flight_discount,hotel_discount,flight_discount_amount,hotel_discount_amount,flight_booked,hotel_booked,page_clicks,cancellation
0,559164-e4d39929bc6040b1b58e2f774b807348,559164,559164-ae58e1fbf8db4f27846fb70c8308ee40,2023-04-02 19:56:00,2023-04-02 19:59:49,False,False,NaN,NaN,True,True,31,False
1,559469-2027a778257341c280db87d26ce9e4e3,559469,559469-aa0fd2b0ee2a403f82e3cf84388c2da3,2023-04-02 12:56:00,2023-04-02 12:57:39,False,False,NaN,NaN,True,False,13,False
2,561331-fb661b0fa33449a187f26b438658a6a5,561331,561331-6478dc007052490e87afee54982c434f,2023-04-02 18:08:00,2023-04-02 18:10:01,False,True,NaN,0.10,True,True,16,False
3,563052-7a1cec53282d404d95495a12bb0de14f,563052,NaN,2023-04-02 20:18:00,2023-04-02 20:19:18,False,True,NaN,0.15,False,False,11,False
4,565460-f25739901563474aa9f4dbad1cc295bf,565460,NaN,2023-04-02 17:09:00,2023-04-02 17:10:35,False,True,NaN,0.10,False,False,13,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49206,543716-c0a36a0263c24262a2ea76f07a8b995f,543716,543716-cefacd82315843a1a083e1bb070e1e11,2023-04-02 20:03:00,2023-04-02 20:05:35,False,False,NaN,NaN,True,True,21,False
49207,545318-3e9a87cf93164fe48f5a650b7dbd35cd,545318,NaN,2023-04-02 20:14:00,2023-04-02 20:16:42,False,False,NaN,NaN,False,False,22,False
49208,549235-32a0d455a8c04e458a621dd2999ea246,549235,NaN,2023-04-02 10:00:00,2023-04-02 10:00:58,False,False,NaN,NaN,False,False,8,False
49209,551600-250e4ebe55b842919c95ea1f995ae652,551600,NaN,2023-04-02 21:32:00,2023-04-02 21:33:15,True,False,0.2,NaN,False,False,10,False
49210,551718-9d071b7f2d0c43dc9d2592eeea827dba,551718,NaN,2023-04-02 01:15:00,2023-04-02 01:15:24,False,False,NaN,NaN,False,False,3,False

In [29]:
sessions["trip_id"].isin(cancelled_trip_ids).sum()

np.int64(1213)

In [31]:
sessions[~sessions["trip_id"].isin(cancelled_trip_ids)]

,session_id,user_id,trip_id,session_start,session_end,flight_discount,hotel_discount,flight_discount_amount,hotel_discount_amount,flight_booked,hotel_booked,page_clicks,cancellation
0,559164-e4d39929bc6040b1b58e2f774b807348,559164,559164-ae58e1fbf8db4f27846fb70c8308ee40,2023-04-02 19:56:00,2023-04-02 19:59:49,False,False,NaN,NaN,True,True,31,False
1,559469-2027a778257341c280db87d26ce9e4e3,559469,559469-aa0fd2b0ee2a403f82e3cf84388c2da3,2023-04-02 12:56:00,2023-04-02 12:57:39,False,False,NaN,NaN,True,False,13,False
2,561331-fb661b0fa33449a187f26b438658a6a5,561331,561331-6478dc007052490e87afee54982c434f,2023-04-02 18:08:00,2023-04-02 18:10:01,False,True,NaN,0.10,True,True,16,False
3,563052-7a1cec53282d404d95495a12bb0de14f,563052,NaN,2023-04-02 20:18:00,2023-04-02 20:19:18,False,True,NaN,0.15,False,False,11,False
4,565460-f25739901563474aa9f4dbad1cc295bf,565460,NaN,2023-04-02 17:09:00,2023-04-02 17:10:35,False,True,NaN,0.10,False,False,13,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49206,543716-c0a36a0263c24262a2ea76f07a8b995f,543716,543716-cefacd82315843a1a083e1bb070e1e11,2023-04-02 20:03:00,2023-04-02 20:05:35,False,False,NaN,NaN,True,True,21,False
49207,545318-3e9a87cf93164fe48f5a650b7dbd35cd,545318,NaN,2023-04-02 20:14:00,2023-04-02 20:16:42,False,False,NaN,NaN,False,False,22,False
49208,549235-32a0d455a8c04e458a621dd2999ea246,549235,NaN,2023-04-02 10:00:00,2023-04-02 10:00:58,False,False,NaN,NaN,False,False,8,False
49209,551600-250e4ebe55b842919c95ea1f995ae652,551600,NaN,2023-04-02 21:32:00,2023-04-02 21:33:15,True,False,0.2,NaN,False,False,10,False
49210,551718-9d071b7f2d0c43dc9d2592eeea827dba,551718,NaN,2023-04-02 01:15:00,2023-04-02 01:15:24,False,False,NaN,NaN,False,False,3,False

In [35]:
valid_session = sessions[~sessions["trip_id"].isin(cancelled_trip_ids)]

In [ ]:
amount_trips_feature = valid_session.groupby("user_id")["trip_id"].nunique() # Feature

user_id
23557     2
94883     2
101486    2
101961    5
106907    0
         ..
792549    4
796032    2
801660    3
811077    1
844489    0
Name: trip_id, Length: 5998, dtype: int64

In [37]:
valid_session.groupby("user_id")["session_id"].nunique()

user_id
23557     8
94883     8
101486    8
101961    8
106907    6
         ..
792549    8
796032    6
801660    8
811077    8
844489    8
Name: session_id, Length: 5998, dtype: int64

In [ ]:
conversion_rate_feature = valid_session.groupby("user_id")["trip_id"].nunique()/valid_session.groupby("user_id")["session_id"].nunique()  # Feature

user_id
23557     0.250000
94883     0.250000
101486    0.250000
101961    0.625000
106907    0.000000
            ...
792549    0.500000
796032    0.333333
801660    0.375000
811077    0.125000
844489    0.000000
Length: 5998, dtype: float64

# Avg Rooms (Violetta)

In [59]:
hotels = pd.read_csv("../data_preprocessed/hotels_preprocessed.csv")

In [61]:
sessions[["user_id", "trip_id"]]

       user_id                                  trip_id
0       559164  559164-ae58e1fbf8db4f27846fb70c8308ee40
1       559469  559469-aa0fd2b0ee2a403f82e3cf84388c2da3
2       561331  561331-6478dc007052490e87afee54982c434f
3       563052                                      NaN
4       565460                                      NaN
...        ...                                      ...
49206   543716  543716-cefacd82315843a1a083e1bb070e1e11
49207   545318                                      NaN
49208   549235                                      NaN
49209   551600                                      NaN
49210   551718                                      NaN

[49211 rows x 2 columns]

In [62]:
hotels = hotels.merge(sessions[["user_id", "trip_id"]], on="trip_id")

In [65]:
hotels

,trip_id,hotel_name,nights,rooms,check_in_time,check_out_time,hotel_per_room_usd,real_nights,hotel_city,user_id
0,118043-3148ad84821c481f81764ed8643adbbf,Fairmont,8,1,2023-07-19 11:00:00.000,2023-07-27 11:00:00,177,8,new york,118043
1,204943-07ddf3a4d2a34e03befdbd07c78d9aab,Aman Resorts,2,3,2023-03-06 09:40:43.050,2023-03-08 11:00:00,230,2,new york,204943
2,229009-406ee07a72a74789bb7b0f5bf0730fe0,Wyndham,2,1,2023-05-27 14:18:53.460,2023-05-29 11:00:00,124,2,edmonton,229009
3,229330-b73ffe29221b40a086cd0107f85eac2b,Extended Stay,2,1,2023-02-26 18:29:05.640,2023-02-28 11:00:00,229,2,san antonio,229330
4,283325-dd763c2d6d334b3790266b500393438e,Wyndham,5,1,2023-03-05 19:18:46.935,2023-03-10 11:00:00,527,5,quebec,283325
...,...,...,...,...,...,...,...,...,...,...
14721,680735-4849063b26ae4997b20d156efc7dc99a,Conrad,2,2,2023-07-24 14:35:10.185,2023-07-26 11:00:00,202,2,winnipeg,680735
14722,698573-1ab935d1f3c146ffbbf6fdeeb2415e33,Conrad,11,1,2023-06-08 13:02:30.300,2023-06-19 11:00:00,306,11,new york,698573
14723,736075-004aa928ddc145cc8f24cfbc6088c8e4,InterContinental,3,1,2023-07-14 13:31:41.655,2023-07-17 11:00:00,147,3,san jose,736075
14724,757930-4dbfad0ba9324d3d81f03e2e24cebfc8,Starwood,5,1,2023-06-10 11:00:00.000,2023-06-15 11:00:00,207,5,edmonton,757930
14725,785107-de5d44027081481297469221ef8794ba,Hyatt,2,1,2023-05-09 14:43:09.750,2023-05-11 11:00:00,191,2,houston,785107

In [64]:
hotels.groupby("user_id")["rooms"].mean()

user_id
23557     1.5
94883     1.5
101486    1.5
101961    1.0
106907    3.0
         ...
785186    1.0
792549    1.0
796032    1.0
801660    1.0
811077    1.0
Name: rooms, Length: 5402, dtype: float64